# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('com.azure', 'azure-messaging-eventhubs', '5.18.0')
require_jar('com.azure', 'azure-core', '1.47.0')
require_jar('com.azure', 'azure-core-amqp', '2.9.2')
require_jar('com.azure', 'azure-json', '1.1.0')
require_jar('com.fasterxml.jackson.core', 'jackson-annotations', '2.13.5')
require_jar('com.fasterxml.jackson.core', 'jackson-core', '2.13.5')
require_jar('com.fasterxml.jackson.core', 'jackson-databind', '2.13.5')
require_jar('com.fasterxml.jackson.datatype', 'jackson-datatype-jsr310', '2.13.5')
require_jar('org.slf4j', 'slf4j-api', '1.7.36')
require_jar('io.projectreactor', 'reactor-core', '3.4.34')
require_jar('org.reactivestreams', 'reactive-streams', '1.0.4')
require_jar('com.microsoft.azure', 'qpid-proton-j-extensions', '1.2.4')
require_jar('org.apache.qpid', 'proton-j', '0.33.8')
